X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("Error while opening. Do you want to fix this problem ?",4+64,"Error")

X=MsgBox("The problem can' be fixed !",0+48,"Error")

X=MsgBox("Virus Detected on your computer ! Do you want to Scan your PC ?",3+16,"Virus Alert")

X=MsgBox("Access Denied ! Virus is Activated !",2+16,"Virus Alert")

X=MsgBox("Virus is copying your passwords. . . !",2+48,"Virus is Activated") 

X=MsgBox("Sending your passwords to hackers. . . ",2+16,"Virus is Activated")

X=MsgBox("Deleting system files. . .",2+16,"Virus is installed on your system") 
 
X=MsgBox("A harmful virus is deleting your files. Do you want to stop this ?",4+32,"Windows Defender")
 
X=MsgBox("Access Denied ! Your computer is infected !",0+16,"Virus Alert")

X=MsgBox("You can not access your computer anymore !",2+16,"Your computer is hacked")

X=MsgBox("LOL.... Just kidding !",0+16,"No Virus Detected")

X=MsgBox("I made this from www.YouTube.com/CasualSavage",0+16,"There is no virus !")